name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./src
      
    - name: Build project
      run: dotnet build --no-restore ./src
      
    - name: Publish release
      run: dotnet publish ./src -c Release -o ./src/Build/

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker
      run: docker build -f ./src/Dockerfile -t cicdtest:latest ./src/Build/
    
    - name: Tag Docker
      run: docker tag cicdtest:latest ${{ secrets.DOCKERHUB_USERNAME }}/cicdtest:latest

    - name: Publish Docker
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cicdtest:latest
          
